name: Playwright Tests
on: push
jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    container: node:20.8.1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: yarn
      - name: Run Puppeteer tests
        run: yarn run-and-test